// Generated by CoffeeScript 1.7.1
var Service;

Service = (function() {
  function Service(client) {
    this._client = client;
  }

  Service.prototype._outputHandler = function(callback) {
    return function(error, payload) {
      if (typeof callback !== 'function') {
        return;
      }
      if (error != null) {
        callback(error);
      } else if (payload.result === 'reject') {
        error = new Error(payload.reason);
        callback(error);
      } else {
        callback(null, payload);
      }
    };
  };

  Service.prototype.accountBalance = function(callback) {
    this._client.invokeMethod('balance', null, this._outputHandler(callback));
    return this;
  };

  Service.prototype.senderList = function(callback) {
    this._client.invokeMethod('senders', null, this._outputHandler(callback));
    return this;
  };

  Service.prototype.addSender = function(name, callback) {
    this._client.invokeMethod('sign', {
      sign: name
    }, this._outputHandler(callback));
    return this;
  };

  Service.prototype.sendMessage = function(options, callback) {
    this._client.invokeMethod('send', options, callback);
    return this;
  };

  Service.prototype.messageStatus = function(id, callback) {
    this._client.invokeMethod('status', {
      id: id
    }, this._outputHandler(callback));
    return this;
  };

  return Service;

})();

module.exports = Service;
